apiVersion: apps/v1
kind: Deployment
metadata:
  name: isi-burger
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: isi-burger
  template:
    metadata:
      labels:
        app: isi-burger
    spec:
      serviceAccountName: isi-burger-sa
      containers:
      - name: app
        image: localhost:5000/isi-burger:7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: APP_ENV
          value: "staging"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_DATABASE
          value: "isi_burger"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/storage
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: app-storage
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config 