apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: isi-burger-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: staging.isi-burger.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: isi-burger-service
            port:
              number: 80 